# Generated by Django 2.1.3 on 2018-11-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockDataCollector', '0003_companynames'),
    ]

    operations = [
        migrations.AddField(
            model_name='companynames',
            name='show_active',
            field=models.BooleanField(null=True),
        ),
    ]
