# Generated by Django 2.1.3 on 2018-11-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockDataCollector', '0004_companynames_show_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynames',
            name='show_active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
