# Generated by Django 2.1.3 on 2018-11-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockDataCollector', '0006_auto_20181104_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynames',
            name='show_active',
            field=models.BooleanField(),
        ),
    ]
